# docker compose -f compose.local.yml --env-file .env.local up -d
# docker compose -f compose.local.yml --env-file .env.local down
services:
  db:
    image: postgres:18-alpine
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}/.docker/volumes/pg_data:/var/lib/postgresql/data
    networks:
      - hoctuvung
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ${PWD}/.docker/volumes/redis_data:/data
    networks:
      - hoctuvung
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']

  qdrant:
    image: qdrant/qdrant:dev
    container_name: qdrant
    ports:
      - '6333:6333'
    networks:
      - hoctuvung
    volumes:
      - ${PWD}/.docker/volumes/qdrant_data:/qdrant/storage

volumes:
  pg_data:
  redis_data:
  qdrant_data:

networks:
  hoctuvung:
