# docker compose -f compose.local.yml --env-file .env.local up -d
services:
  db:
    image: postgres:18-alpine
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}/.docker/volumes/pg_data:/var/lib/postgresql/data
    networks:
      - freelet
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ${PWD}/.docker/volumes/redis_data:/data
    networks:
      - freelet
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']

volumes:
  pg_data:
  redis_data:

networks:
  freelet:
