# docker compose -f compose.local.yml --env-file .env.local up -d
services:
  database:
    image: postgres:18-alpine
    container_name: database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - app

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    volumes:
      - redis_data:/data
    networks:
      - app

volumes:
  database_data:
  redis_data:

networks:
  app:
